<!DOCTYPE html>
<html lang>
  <head><meta name="generator" content="Hexo 3.9.0">
    
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1,minimum-scale=1,maximum-scale=1">


<meta http-equiv="Cache-Control" content="no-transform">
<meta http-equiv="Cache-Control" content="no-siteapp">



  <meta name="description" content="Java里面的异常">




  <meta name="keywords" content="JavaBasics,">





  <link rel="alternate" href="/default" title="Illusory">




  <link rel="shortcut icon" type="image/x-icon" href="/favicon.ico?v=1.1">



<link rel="canonical" href="http://yaoper.github.io/2020/04/13/Java里面的异常/">


<meta name="description" content="Java的基本设计理念认为，结构不佳的代码不能运行。发现错误的最佳时期应该是在编译期间。因为你不用运行程序就能发现问题。但是编译期间并不能找出所有的问题，比如NullPointerException 和 ClassNotFoundException 在编译期找不到，这些异常是 RuntimeException 运行时异常，这些异常往往在运行时才能被发现。  Java 程序经常会出现两种问题，一种是">
<meta name="keywords" content="JavaBasics">
<meta property="og:type" content="article">
<meta property="og:title" content="Java里面的异常">
<meta property="og:url" content="http://yaoper.github.io/2020/04/13/Java里面的异常/index.html">
<meta property="og:site_name" content="Illusory">
<meta property="og:description" content="Java的基本设计理念认为，结构不佳的代码不能运行。发现错误的最佳时期应该是在编译期间。因为你不用运行程序就能发现问题。但是编译期间并不能找出所有的问题，比如NullPointerException 和 ClassNotFoundException 在编译期找不到，这些异常是 RuntimeException 运行时异常，这些异常往往在运行时才能被发现。  Java 程序经常会出现两种问题，一种是">
<meta property="og:locale" content="zh-Hans">
<meta property="og:updated_time" content="2020-04-14T03:55:18.699Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Java里面的异常">
<meta name="twitter:description" content="Java的基本设计理念认为，结构不佳的代码不能运行。发现错误的最佳时期应该是在编译期间。因为你不用运行程序就能发现问题。但是编译期间并不能找出所有的问题，比如NullPointerException 和 ClassNotFoundException 在编译期找不到，这些异常是 RuntimeException 运行时异常，这些异常往往在运行时才能被发现。  Java 程序经常会出现两种问题，一种是">


<link rel="stylesheet" type="text/css" href="/css/style.css?v=1.1">
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">





<script type="text/javascript">
  var themeConfig = {
    fancybox: {
      enable: false
    },
  };
</script>




  



    <title> Java里面的异常 - Illusory </title>
  </head>

  <body>
    <div id="page">
      <header id="masthead"><div class="site-header-inner">
    <h1 class="site-title">
        <a href="/." class="logo">Illusory</a>
    </h1>

    <nav id="nav-top">
        
            <ul id="menu-top" class="nav-top-items">
                
                    <li class="menu-item">
                        <a href="/archives">
                            
                            
                                Archives
                            
                        </a>
                    </li>
                
                    <li class="menu-item">
                        <a href="/about">
                            
                            
                                About
                            
                        </a>
                    </li>
                
            </ul>
        
  </nav>
</div>

      </header>
      <div id="content">
        
    <div id="primary">
        
  <article class="post">
    <header class="post-header">
      <h1 class="post-title">
        
          Java里面的异常
        
      </h1>

      <time class="post-time">
          Apr 13 2020
      </time>
    </header>



    
            <div class="post-content">
            <p>Java的基本设计理念认为，结构不佳的代码不能运行。发现错误的最佳时期应该是在编译期间。因为你不用运行程序就能发现问题。但是编译期间并不能找出所有的问题，比如NullPointerException 和 ClassNotFoundException 在编译期找不到，这些异常是 RuntimeException 运行时异常，这些异常往往在运行时才能被发现。 </p>
<p>Java 程序经常会出现两种问题，一种是 java.lang.Exception ，一种是 java.lang.Error，都用来表示出现了异常情况，下面就针对这两种概念进行理解。 </p>
<h3 id="1-Exception"><a href="#1-Exception" class="headerlink" title="1. Exception"></a>1. Exception</h3><p><code>Exception</code> 位于 <code>java.lang</code> 包下，它是一种顶级接口，继承于 <code>Throwable</code> 类，Exception 类及其子类都是 Throwable 的组成条件，是程序出现的合理情况。 </p>
<h4 id="1-1-Throwable"><a href="#1-1-Throwable" class="headerlink" title="1.1 Throwable"></a>1.1 Throwable</h4><p>Throwable 类是 Java 语言中所有<code>错误(errors)</code>和<code>异常(exceptions)</code>的父类。只有继承于 Throwable 的类或者其子类才能够被抛出，还有一种方式是带有 Java 中的 <code>@throw</code> 注解的类也可以抛出。 除了 <code>RuntimeException</code> 和其子类，以及<code>error</code>和其子类，其它的所有异常都是 <code>checkedException</code>。 </p>
<p>我们看一下Throwable类中比较常见的一些方法</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br></pre></td><td class="code"><pre><span class="line"><span class="comment">// 返回抛出异常的详细信息</span></span><br><span class="line"><span class="function"><span class="keyword">public</span> string <span class="title">getMessage</span><span class="params">()</span></span>;</span><br><span class="line"><span class="function"><span class="keyword">public</span> string <span class="title">getLocalizedMessage</span><span class="params">()</span></span>;</span><br><span class="line"></span><br><span class="line"><span class="comment">//返回异常发生时的简要描述</span></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">public</span> String <span class="title">toString</span><span class="params">()</span>；</span></span><br><span class="line"><span class="function">  </span></span><br><span class="line"><span class="function"><span class="comment">// 打印异常信息到标准输出流上</span></span></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">printStackTrace</span><span class="params">()</span></span>;</span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">printStackTrace</span><span class="params">(PrintStream s)</span></span>;</span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">void</span> <span class="title">printStackTrace</span><span class="params">(PrintWriter s)</span></span></span><br><span class="line"><span class="function"></span></span><br><span class="line"><span class="function"><span class="comment">// 记录栈帧的的当前状态</span></span></span><br><span class="line"><span class="function"><span class="keyword">public</span> <span class="keyword">synchronized</span> Throwable <span class="title">fillInStackTrace</span><span class="params">()</span></span>;</span><br></pre></td></tr></table></figure>

<p>此外，因为 Throwable 的父类也是 <code>Object</code>，所以常用的方法还有继承其父类的<code>getClass()</code> 和<code>getName()</code> 方法。 </p>
<h4 id="1-2-常见的Exception"><a href="#1-2-常见的Exception" class="headerlink" title="1.2 常见的Exception"></a>1.2 常见的Exception</h4><p>我们知道Exception的父类是Throwable，并且Exception有两种异常，一种是 <code>RuntimeException</code> ；一种是 <code>CheckedException</code>，这两种异常都应该去捕获。 </p>
<p><strong>RuntimeException</strong></p>
<table>
<thead>
<tr>
<th>序号</th>
<th>异常名称</th>
<th>异常描述</th>
</tr>
</thead>
<tbody><tr>
<td>1</td>
<td>ArrayIndexOutOfBoundsException</td>
<td>数组越界异常</td>
</tr>
<tr>
<td>2</td>
<td>NullPointerException</td>
<td>空指针异常</td>
</tr>
<tr>
<td>3</td>
<td>IllegalArgumentException</td>
<td>非法参数异常</td>
</tr>
<tr>
<td>4</td>
<td>NegativeArraySizeException</td>
<td>数组长度为负异常</td>
</tr>
<tr>
<td>5</td>
<td>IllegalStateException</td>
<td>非法状态异常</td>
</tr>
<tr>
<td>6</td>
<td>ClassCastException</td>
<td>类型转换异常</td>
</tr>
</tbody></table>
<p><strong>UncheckedException</strong></p>
<table>
<thead>
<tr>
<th>序号</th>
<th>异常名称</th>
<th>异常描述</th>
</tr>
</thead>
<tbody><tr>
<td>1</td>
<td>NoSuchFieldException</td>
<td>表示该类没有指定名称抛出来的异常</td>
</tr>
<tr>
<td>2</td>
<td>NoSuchMethodException</td>
<td>表示该类没有指定方法抛出来的异常</td>
</tr>
<tr>
<td>3</td>
<td>IllegalAccessException</td>
<td>不允许访问某个类的异常</td>
</tr>
<tr>
<td>4</td>
<td>ClassNotFoundException</td>
<td>类没有找到抛出异常</td>
</tr>
</tbody></table>
<h4 id="1-3-与Exception相关的关键字"><a href="#1-3-与Exception相关的关键字" class="headerlink" title="1.3 与Exception相关的关键字"></a>1.3 与Exception相关的关键字</h4><p>Java中异常处理相关的关键字有<strong>throws、throw、try、finally、catch</strong>，下面我们来探讨下。</p>
<p><strong>throws 和 throw</strong></p>
<p>在 Java 中，异常也就是一个对象，它能够被程序员自定义抛出或者应用程序抛出，必须借助于 <code>throws</code> 和 <code>throw</code> 语句来定义抛出异常。 通常情况下他们是成对出现的。</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">static</span> <span class="keyword">void</span> <span class="title">cacheException</span><span class="params">()</span> <span class="keyword">throws</span> Exception</span>&#123;</span><br><span class="line">	<span class="keyword">throw</span> <span class="keyword">new</span> Exception();</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<p>throw 语句用在方法体内，表示抛出异常，由方法体内的语句处理。throws 语句用在方法声明后面，表示再抛出异常，由该方法的调用者来处理。</p>
<p>throws 主要是声明这个方法会抛出这种类型的异常，使它的调用者知道要捕获这个异常。throw 是具体向外抛异常的动作，所以它是抛出一个异常实例。</p>
<p><strong>try 、catch、finally</strong> </p>
<p>这三个关键字主要有下面几种组合方式 <strong>try…catch 、try…finally、try…catch…finally</strong>。 </p>
<p>try…catch 表示对某一段代码可能抛出异常进行的捕获。</p>
<p>try…finally 表示对一段代码不管执行情况如何，都会走 finally 中的代码。</p>
<p>try…catch…finally 也是一样的，表示对异常捕获后，再走 finally 中的代码逻辑。</p>
<p>JDK1.7 使用 try…with…resources 优雅关闭资源，示例如下：</p>
<figure class="highlight java"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br></pre></td><td class="code"><pre><span class="line"><span class="function"><span class="keyword">static</span> String <span class="title">firstLineOfFileAutoClose</span><span class="params">(String path)</span> <span class="keyword">throws</span> IOException </span>&#123;</span><br><span class="line">  <span class="keyword">try</span>(BufferedReader br = <span class="keyword">new</span> BufferedReader(<span class="keyword">new</span> FileReader(path)))&#123;</span><br><span class="line">    <span class="keyword">return</span> br.readLine();</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>

<h4 id="1-4-异常处理原则"><a href="#1-4-异常处理原则" class="headerlink" title="1.4 异常处理原则"></a>1.4 异常处理原则</h4><ul>
<li>不要捕获类似 <code>Exception</code> 之类的异常，而应该捕获类似特定的异常，比如 <code>InterruptedException</code>，方便排查问题。 </li>
<li>不要生吞异常。这是异常处理中要特别注重的事情。如果我们不把异常抛出来，或者也没有输出到 Logger 日志中，程序可能会在后面以不可控的方式结束。 </li>
<li>不要在函数式编程中使用 <code>checkedException</code>。 </li>
</ul>
<h3 id="2-Error"><a href="#2-Error" class="headerlink" title="2. Error"></a>2. Error</h3><p>Error 是程序无法处理的错误，表示运行应用程序中较严重问题。大多数错误与代码编写者执行的操作无关，而表示代码运行时 JVM（Java 虚拟机）出现的问题。这些错误是不可检查的，因为它们在应用程序的控制和处理能力之 外，而且绝大多数是程序运行时不允许出现的状况，比如 <code>OutOfMemoryError</code> 和 <code>StackOverflowError</code>异常 。</p>
<h4 id="2-1-面试题"><a href="#2-1-面试题" class="headerlink" title="2.1 面试题"></a>2.1 面试题</h4><p><strong>NoClassDefFoundError 和 ClassNotFoundException 有什么区别</strong>？ </p>
<p>在类的加载过程中， JVM 或者 ClassLoader 无法找到对应的类时，都可能会引起这两种异常/错误，由于不同的 ClassLoader 会从不同的地方加载类，有时是错误的 CLASSPATH 类路径导致的这类错误，有时是某个库的 jar 包缺失引发这类错误。NoClassDefFoundError 表示这个类在编译时期存在，但是在运行时却找不到此类，有时静态初始化块也会导致 NoClassDefFoundError 错误。 </p>
<p>另一方面，ClassNotFoundException 与编译时期无关，当你尝试在运行时使用反射加载类时，ClassNotFoundException 就会出现。</p>
<p>简而言之，ClassNotFoundException 和 NoClassDefFoundError 都是由 CLASSPATH 中缺少类引起的，通常是由于缺少 JAR 文件而引起的，但是如果 JVM 认为应用运行时找不到相应的引用，就会抛出 NoClassDefFoundError 错误；当你在代码中显示的加载类比如 <code>Class.forName()</code> 调用时却没有找到相应的类，就会抛出 <code>java.lang.ClassNotFoundException</code>。</p>

            </div>
          

    
      <footer class="post-footer">
		
		<div class="post-tags">
		  
			<a href="/tags/JavaBasics/">JavaBasics</a>
		  
		</div>
		

        
        
  <nav class="post-nav">
    
      <a class="prev" href="/2020/04/14/Redis-Clsuter/">
        <i class="iconfont icon-left"></i>
        <span class="prev-text nav-default">Redis Clsuter</span>
        <span class="prev-text nav-mobile">Prev</span>
      </a>
    
    
      <a class="next" href="/2020/04/13/Redis的分布式锁/">
        <span class="next-text nav-default">Redis的分布式锁</span>
        <span class="prev-text nav-mobile">Next</span>
        <i class="iconfont icon-right"></i>
      </a>
    
  </nav>

        
  <div class="comments" id="comments">
    
  </div>


      </footer>
    
  </article>

    </div>

      </div>

      <footer id="colophon"><span class="copyright-year">
    
        &copy;
    
        2014 -
    
    2020
    <span class="footer-author">yaoper.</span>
    <span class="power-by">
        Powered by <a class="hexo-link" href="https://hexo.io/">Hexo</a> and <a class="theme-link" href="https://github.com/frostfan/hexo-theme-polarbear">Polar Bear</a>
    </span>
</span>

      </footer>

      <div class="back-to-top" id="back-to-top">
        <i class="iconfont icon-up"></i>
      </div>
    </div>
    


    




  
    <script type="text/javascript" src="/lib/jquery/jquery-3.1.1.min.js"></script>
  

  

    <script type="text/javascript" src="/js/src/theme.js?v=1.1"></script>
<script type="text/javascript" src="/js/src/bootstrap.js?v=1.1"></script>

  </body>
</html>
